### PR TITLE
Overfunding validation

### PR DESCRIPTION
**Pull request by rajeshvaya**

### CODE REVIEW

**Comment by ritenv** [comment]
Yo, are we not already subtracting the funds held from the main balance? So the main balance is the actual amount the user can use, already... right?

**Comment by rajeshvaya** [comment]
umm true, I don't why i did that :| cool I will fix it

**Comment by rajeshvaya** [comment]
Reverted

**Comment by ritenv** [comment]
:+1:

**Comment by ritenv** [comment]
Why not merged to master? The rest is useful right..

**Comment by rajeshvaya** [comment]
yea i created a new pull request, i realized it later we could have committed to this one :D

**Pull request closed without merging**
